config/routes.rb
Basecampclone::Application.routes.draw do
  devise_for :users
  resources :projects do
    resources :todos
  end
  resources :todos do
    resources :tasks
  end
  root :to => "projects#index"
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :public, :user_id, :todos_attributes
  
  belongs_to :user
  
  validates_presence_of :name, :user_id
  
  has_many :todos
  
  accepts_nested_attributes_for :todos
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :due_date, :todo_id
  
  belongs_to :todo
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :name, :project_id, :tasks_attributes
  
  has_many :tasks
  
  accepts_nested_attributes_for :tasks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  validates_uniqueness_of :email
  
  has_many  :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @project = Project.new
    if user_signed_in?
      @private_projects = Project.find_all_by_user_id(current_user.id)
    end
      @public_projects = Project.find_all_by_public(true)
  end
  
  def new
   
    @project = Project.new
    @todo = Todo.new
    3.times { @project.todos.build } 
    @todo.tasks.build
  end
  
  def create
    @project = Project.new(params[:project])
    @project.user_id = current_user.id
    if @project.save
      respond_to do |format|
        format.html { redirect_to @project; flash[:success] = "Project created." }
        format.js
      end
    else
      flash[:error] = "Something went wrong"
      render :new
    end
  end
  
  def show
     @project = Project.find(params[:id])
     @todo = Todo.new
     @task = Task.new
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.todo.update_attributes(params[:project])
      flash[:success] = "Successful Edit"
      redirect_to project_path
    else
      flash[:error] = "Something went wrong"
      render :new
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])
  end

  def edit
    @task = Task.new(params[:task])
  end

  def update

  end

  def destroy

  end

  def index

  end

  def show

  end

end
  

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  
  def new
    @todo = Todo.new
  end
  
  def create
    @todo = Todo.new(params[:todo])
    if @todo.save
      respond_to do |format|
        format.html { redirect_to @todo; flash[:success] = "Todo created." }
        format.js
      end
    else
      flash[:error] = "Something went wrong"
      render :new
    end
  end
  
  def edit
    @project = Project.find(params[:id])
    audit "edit params"
    audit params
    @todo = Todo.find(params[:id])
  end
  
  def update
    audit "update controller params hash"
    audit params
    @project = Project.find(params[:id])
    @todo = Todo.find(params[:id])
    @todo.update_attributes(params[:todo])
    @todo.save
    audit "update controller trigered"
    audit params
    redirect_to project_path(params[:id])
  end
  
  def destroy
    audit "destroy controller triggered"
    audit params
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to project_path(params[:id])
  end
  
  def index
    
  end
  
  def show
    
  end
  
end
# <h1><%= @todo.name %></h1>
#   <%= form_for @todo do |p| %>
#     <%= p.label "Todo Name" %>
#     <%= p.text_field :name %>
#     <%= p.fields_for :tasks, @todo.tasks do |tsk| %>
#     <%= tsk.label "Task name, sucka" %>
#     <%= tsk.text_field :description %>
#     <% end %>
#     <%= p.hidden_field :id, :value => @todo[:project_id]%>
#     <%= p.submit "Submit", class: "btn btn-primary" %>
#   <% end %>

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
     <div class="container">
       <ul class="nav">
         <% if user_signed_in? %>
         <li><%= link_to "Projects", projects_path %></li>
         <li><%= link_to "New Project", new_project_path %></li>
         <li><%= link_to "Sign out",  destroy_user_session_path, :method => :delete %></li>
         <% elsif %>

          <li><%= link_to "Projects", projects_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
     </div>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Basecampclone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body><%= render "layouts/header"%>
  <div class="flash">
    <%= render 'layouts/errors' %>
  </div>

  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span2">
        
      </div>
      <div class="span6">
      <%= yield %>
      </div>
      
      <div class="span6">
      <%= render "layouts/footer" %>
      </div>
  </div>
</div>

</body>
</html>

app/views/projects/_add_todo.erb
<h2>Add Todo</h2><br>
<%= form_for @todo, :remote => true do |p| %>
  <%= p.label "Todo Name" %>
  <%= p.text_field :name %>
  <%= p.fields_for :tasks, @todo.tasks do |tsk| %>
    <%= tsk.label "Task name, sucka" %>
    <%= tsk.text_field :description %>
    <% end %>
  <%= p.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/projects/_project_partial.erb
<h1>Make a new Project</h1><br>
<%= form_for @project,:remote => true do |p| %>
  <%= p.label "Project Name" %>
  <%= p.text_field :name  %>
  <%= p.fields_for :todos, @project.todos do |tf| %>
    <%= tf.label "Todo name" %>
    <%= tf.text_field :name %>
    <%= tf.fields_for :tasks, @todo.tasks do |tsk| %>
    <%= tsk.label "Task name, sucka" %>
    <%= tsk.text_field :description %>
    <% end %>
  <% end %>
 <label class="checkbox"><%= p.check_box :public %><%= p.label "Set to Public?" %></label>
  <br/>
  <%= p.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/projects/_projects.html.erb
<ul>
<%= projects.each do |project| %>
 <li><%= project.name %></li>
<% end %>
</ul>

app/views/projects/create.js.erb
$('#private').append('<li><%= link_to @project.name, project_path(@project) %></li>');
$('#new_project')[0].reset();

app/views/projects/index.html.erb
<h1>Projects</h1>
<% if @private_projects %>
  <h2>Private Projects</h2>
  <ul id="private">
  <% @private_projects.each do |project| %>
    <li><%= link_to "#{project.name}", project_path(project) %></li>
  <% end %>
</ul>
<% end %>
<h2>Public Projects</h2>
<ul>
<% @public_projects.each do |project| %>
<li><%= link_to "#{project.name}", project_path(project) %></li>
<% end %>
</ul>

<%= render "project_partial" %>

app/views/projects/new.html.erb
<h1>Make a new Project</h1><br>
<%= form_for @project do |p| %>
  <%= p.label "Project Name" %>
  <%= p.text_field :name %>
  <%= p.fields_for :todos, @project.todos do |tf| %>
    <%= tf.label "Todo name" %>
    <%= tf.text_field :name %>
    <%= tf.fields_for :tasks, @todo.tasks do |tsk| %>
    <%= tsk.label "Task name, sucka" %>
    <%= tsk.text_field :description %>
    <% end %>
  <% end %>
 <label class="checkbox"><%= p.check_box :public %><%= p.label "Set to Public?" %></label>
  <br/>
  <%= p.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<% @project.todos.each do |todo| %>
<div id="todos">
<h2><%= todo.name %> <%= link_to "Edit", edit_project_todo_path(@project, todo.id), class: "btn btn-mini btn-warning"%>
   <%= link_to "Delete", project_todo_path(@project, todo), class: "btn btn-danger btn-mini", :method => :delete %></h2>
<ul>
<% todo.tasks.each do |tsk| %>
  <li><%= tsk.description %></li>
<% end %>
</ul>
</div>
<% end %>
<%= render 'add_todo' %>
<%= link_to "add todo", "#addtodostuff" %> | 
<%= link_to "add task", "#addtodostuff" %>

app/views/todos/create.js.erb
$('#todos').append('<li><%= link_to @todo.name, project_path(@project) %></li>');
$('#new_todo')[0].reset();

app/views/todos/edit.html.erb
  
 <h1><%= @todo.name %></h1>
  <%= form_for @project do |p| %>
    <%= p.label "Project Name" %>
    <%= p.text_field :name %>
    <%= p.fields_for :todos, @project.todos do |tf| %>
      <%= tf.label "Todo name" %>
      <%= tf.text_field :name %>
      <%= tf.fields_for :tasks, @todo.tasks do |tsk| %>
      <%= tsk.label "Task name, sucka" %>
      <%= tsk.text_field :description %>
      <% end %>
    <% end %>
   <label class="checkbox"><%= p.check_box :public %><%= p.label "Set to Public?" %></label>
    <br/>
    <%= p.submit "Submit", class: "btn btn-primary" %>
  <% end %>

app/views/todos/new.html.erb
new todo

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<%= form_for @user do |p| %>
  <%= p.label "User Email" %>
  <%= p.text_field :email %>
  <%= p.label "Password" %>
  <%= p.text_field :password %>
  <%= p.submit "Create" %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>